export const TRIPS = [
  {
    id: "zagros",
    tag: "THE ANCIENT WAY",
    name: "Zagros Mountain Trail",
    tagColor: "var(--vik-sage)",
    difficulty: "Moderate-Hard",
    diffClass: "diff-hard",
    duration: "13 Days",
    price: "$2,500",
    priceNote: "per person",
    nextDate: "March 19-31, 2026",
    image: "/images/ski-touring.jpg",
    shortDesc: "Iraq's first long-distance hiking route. 215 km across ancient paths, 30+ villages, canyon walks, and alpine ridges from Shush to the foot of Mount Halgurd.",
    flagship: true,
  },
  {
    id: "summit",
    tag: "TOUCH THE SKY",
    name: "Halgurd Summit Expedition",
    tagColor: "var(--vik-sage-light)",
    difficulty: "Expert",
    diffClass: "diff-expert",
    duration: "2-3 Days",
    price: "Contact us",
    image: "/images/IMG_4332.jpg",
    shortDesc: "Conquer Iraq's rooftop at 3,607m. Snow fields, scrambling, sunrise over three countries.",
  },
  {
    id: "fullday",
    tag: "WALK WITH EAGLES",
    name: "Halgurd Full-Day Trek",
    tagColor: "var(--vik-warm)",
    difficulty: "Challenging",
    diffClass: "diff-hard",
    duration: "8-12 Hours",
    price: "From $150",
    image: "/images/IMG_4454.jpg",
    shortDesc: "Base camp & upper alpine meadows at 2,500-3,000m without the technical summit push.",
  },
  {
    id: "halfday",
    tag: "VALLEY OF LEGENDS",
    name: "Halgurd Half-Day Hike",
    tagColor: "var(--vik-glacier)",
    difficulty: "Moderate",
    diffClass: "diff-moderate",
    duration: "4-5 Hours",
    price: "From $150",
    priceNote: "min 3 people",
    image: "/images/IMG_4133.jpg",
    shortDesc: "Green meadows, orchards & streams through the lower Halgurd valley.",
  },
  {
    id: "quarter",
    tag: "MOUNTAIN WHISPER",
    name: "Halgurd Sunrise Walk",
    tagColor: "var(--vik-glacier-light)",
    difficulty: "Easy",
    diffClass: "diff-easy",
    duration: "2-3 Hours",
    price: "From $150",
    priceNote: "min 3 people",
    image: "/images/IMG_4328.jpg",
    shortDesc: "Gentle foothills & wildflower trails. Ideal for photography and families.",
  },
  {
    id: "gomi",
    tag: "MIRROR OF THE GODS",
    name: "Gomi Felaw Lake Trek",
    tagColor: "var(--vik-storm-bright)",
    difficulty: "Moderate",
    diffClass: "diff-moderate",
    duration: "Day Trip",
    price: "From $150",
    priceNote: "min 3 people",
    image: "/images/IMG_4448.jpg",
    shortDesc: "Kurdistan's highest alpine lake at 3,000m between Sikal and Hisar mountains.",
  },
];

export const ZMT_DAYS = [
  {
    label: "Day 1",
    date: "March 19",
    title: "Arrival in Erbil & City Tour",
    description: "Arrive at Erbil International Airport where your VIKurdistan guide will greet you. Transfer to the hotel for a welcome briefing, then explore the ancient Erbil Citadel — one of the oldest continuously inhabited sites on earth (6,500+ years). Wander through traditional bazaars alive with color, spice, and Kurdish hospitality. End with an authentic dinner of kebab, dolma, and fresh bread.",
    overnight: "Overnight in Erbil",
  },
  {
    label: "Day 2",
    date: "March 20 — Nawroz Eve",
    title: "Erbil → Shush → Akre & Nawroz Celebration",
    description: "Drive to the village of Shush to begin your trek. Walk Stage 1 through scenic countryside. Arrive in Akre for the legendary Nawroz celebration — thousands of flames light up the mountainside as communities gather for music, dancing, fire-lighting ceremonies, and cultural festivities that mark the Kurdish New Year.",
    overnight: "Overnight in Akre homestay",
  },
  {
    label: "Day 3",
    date: "March 21",
    title: "Akre → Hashga → Safti Village",
    description: "Hike Stage 2 & 3 through rolling hills and serene landscapes. The trail meanders through pine forests and past ancient ruins — church remnants and a synagogue under restoration remind you that these mountains have hosted diverse communities for millennia. Arrive in Safti village as the sun paints the hills golden.",
    overnight: "Overnight in Safti homestay",
  },
  {
    label: "Days 4-6",
    date: "March 22-24",
    title: "Safti → Alka → Harbo → Khalan",
    description: "Three days of pure mountain magic. Walk through lush valleys where streams cut through green pastures, climb high ridgelines with panoramic views stretching to the horizon, and follow riverside paths beneath dramatic mountain walls. Each night, a new village. Each meal, a feast — fresh bread from clay ovens, lamb slow-cooked over open flame.",
    overnight: "Overnights in Alka, Harbo & Khalan",
  },
  {
    label: "Days 7-9",
    date: "March 25-27",
    title: "Khalan → Soran → Rawanduz → Dargala",
    description: "Enter some of the trail's most spectacular terrain. Stage 7 through mountain forests is widely considered the trail's most impressive section. Pass through the dramatic Rawanduz Canyon — towering cliff walls frame a river far below. The landscape grows wilder, the air thinner, the views more staggering with every step.",
    overnight: "Overnights in Soran, Saran & Dargala",
  },
  {
    label: "Days 10-11",
    date: "March 28-29",
    title: "Dargala → Rezan → Choman",
    description: "The final approach. Hike through scenic river valleys and cross streams as the mighty silhouettes of Halgurd and Sakran mountains grow larger on the horizon. Arrive in Choman — the charming mountain town where VIKurdistan was born. Meet Omar's community, explore the local market, and rest before the grand finale.",
    overnight: "Overnights in Rezan & Choman",
  },
  {
    label: "Day 12",
    date: "March 30 — The Grand Finale",
    title: "Choman → Halgurd Base Camp → Choman",
    description: "The moment the entire trail has been building toward. Walk Stage 12 — a high alpine ascent into the scenic highlands beneath Mount Halgurd, Iraq's tallest peak (3,607m). Pass remote stone dwellings, cross mountain streams, walk through wildflower meadows, and enter a landscape of raw, untouched alpine beauty. This is the rooftop of Iraq.",
    overnight: "Overnight in Choman — celebration dinner",
  },
  {
    label: "Day 13",
    date: "March 31",
    title: "Return to Erbil & Departure",
    description: "After breakfast with your Choman hosts, drive back through the spectacular mountain roads to Erbil. Transfer to Erbil International Airport. You'll carry home more than photos — the taste of mountain honey, the sound of Kurdish music, the warmth of families who opened their homes, and the knowledge that you walked one of the world's last undiscovered great trails.",
    overnight: "End of trek",
  },
];

export const DESTINATIONS = [
  {
    name: "Kani Bast Waterfall",
    description: "The \"frozen waterfall\" — up to 50 meters high at nearly 2,000m elevation. So iconic it's printed on the 50,000 Iraqi Dinar banknote. Water temperature never exceeds 20°C even in peak summer.",
    location: "Between Choman & Soran",
    icon: "💎",
  },
  {
    name: "Rawanduz Canyon",
    description: "A 10-kilometer gorge near the Iranian border where towering cliff walls frame rushing rivers far below. Green from spring to autumn, draped in waterfalls. One of the most dramatic canyons in the Middle East.",
    location: "En route Erbil to Choman",
    icon: "🏔️",
  },
  {
    name: "Bekodyan Pond",
    description: "At 3,200 meters on Hasari Sakran Mountain — Kurdistan's highest natural site. Snow persists even in July. A 7-10 hour trek rewards the truly adventurous with the most remote spot in all of Iraq.",
    location: "Balakayati region",
    icon: "⭐",
  },
  {
    name: "Gali Ali Beg Waterfall",
    description: "Iraq's highest waterfall, drawing 500,000 visitors yearly. Named after the Yazidi prince Mir Ali Beg. Once featured on the Iraqi 5-dinar note. Three rivers converge here in a thunderous display.",
    location: "130km from Erbil, en route",
    icon: "🌊",
  },
  {
    name: "Haji Omaran",
    description: "20km from Choman at the Iraq-Iran border, sitting at 1,900m. Hills, streams, and meadows surrounded by mountains. One of the most scenic border crossings in the world.",
    location: "20km east of Choman",
    icon: "🌿",
  },
  {
    name: "Rost Valley & Citadel",
    description: "At the foot of Halgurd, blessed with fresh water, forests, and orchards. A small river passes through. Above, the ancient Rost Citadel — an archaeological treasure with sweeping mountain views.",
    location: "Soran-Choman highway",
    icon: "🏰",
  },
];

export const HALGURD_LEVELS = [
  {
    tag: "TOUCH THE SKY",
    name: "Summit Expedition",
    tagColor: "text-[var(--vik-sage)]",
    difficulty: "Expert",
    diffClass: "diff-expert",
    duration: "2-3 Days",
    elevation: "+1,455m elevation",
    extra: "Guide required",
    image: "/images/IMG_4332.jpg",
    description: "The full summit push to 3,607 meters. Trek from Choman to base camp, camp overnight, then summit at dawn for sunrise views across three countries — Iraq, Iran, and Turkey. Scrambling sections, snow fields, and the raw power of standing on Iraq's highest point.",
  },
  {
    tag: "WALK WITH EAGLES",
    name: "Full-Day Trek",
    tagColor: "text-[var(--vik-warm)]",
    difficulty: "Challenging",
    diffClass: "diff-hard",
    duration: "8-12 Hours",
    elevation: "Moderate-Hard",
    extra: "Good fitness required",
    image: "/images/IMG_4454.jpg",
    description: "Reach the upper alpine meadows and base camp area at 2,500-3,000m without the technical summit push. Pass remote stone dwellings, cross mountain streams, and walk through seas of wildflowers beneath the towering peak.",
  },
  {
    tag: "VALLEY OF LEGENDS",
    name: "Half-Day Hike",
    tagColor: "text-[var(--vik-glacier)]",
    difficulty: "Moderate",
    diffClass: "diff-moderate",
    duration: "4-5 Hours",
    elevation: "Family-friendly",
    extra: "All fitness levels",
    image: "/images/IMG_4133.jpg",
    description: "Follow the valley road out of Choman into a world of green meadows, ancient orchards, and crystal-clear streams. The path follows a water channel through the lower valley with Halgurd's snow-capped peak always watching from above.",
  },
  {
    tag: "MOUNTAIN WHISPER",
    name: "Sunrise Walk",
    tagColor: "text-[var(--vik-glacier-light)]",
    difficulty: "Easy",
    diffClass: "diff-easy",
    duration: "2-3 Hours",
    elevation: "Easy",
    extra: "Great for photography",
    image: "/images/IMG_4328.jpg",
    description: "A gentle morning walk through the Halgurd foothills. Wildflower meadows bloom in spring, pastoral scenery unfolds in every direction, and the mountain air is impossibly fresh. Ideal for photographers, families, or casual visitors.",
  },
];

export const STAYS = [
  {
    name: "Mountain Glamping",
    description: "Fall asleep to mountain wind in a warm bell tent on a wooden deck. Step outside to a sky full of stars you've never seen. Includes wood stove heating, comfortable bedding, and outdoor seating.",
    price: "From $200",
    priceNote: "/night",
    location: "Przhe Village, 2,000m",
    image: "/images/IMG_4105.jpg",
  },
  {
    name: "Choman Mountain Villas",
    description: "Private mountain villas with pools, panoramic views, and modern amenities. Red House (35+ guests, 360° view), Blue House (indoor pool), or Yellow House (intimate garden).",
    price: "From $100",
    priceNote: "/night",
    location: "Nawroen Resort, Choman",
    image: "/images/IMG_4129.jpg",
  },
  {
    name: "Village Homestays",
    description: "Sleep in a Kurdish family home, share meals around a communal spread, drink endless chai, and leave as family. Available along the ZMT and in Choman itself.",
    price: "Included",
    priceNote: " with tours",
    location: "ZMT villages & Choman",
    image: "/images/IMG_4133.jpg",
  },
];

export const FAQ_ITEMS = [
  {
    question: "Is it safe to travel to Kurdistan?",
    answer: "Yes. The Kurdistan Region of Iraq is safe and welcoming to tourists. It has its own government, security forces, and visa policies separate from federal Iraq. VIKurdistan has been operating safely for 13+ years. All accommodations are verified, guides are professional, and permits are secured for every stage of your journey.",
  },
  {
    question: "Do I need hiking experience for the Zagros Trail?",
    answer: "The trail covers moderate to challenging terrain. Previous hiking experience is recommended but not required — our professional guide ensures safety and support throughout. The itinerary balances trekking with rest days and cultural activities. For easier options, try our half-day or quarter-day Halgurd hikes.",
  },
  {
    question: "How do I get to Choman?",
    answer: "Fly into Erbil International Airport. We handle everything from there — airport pickup, 3-4 hour scenic drive through Rawanduz Canyon to Choman, and return transport. The drive itself is spectacular, passing Bekhal Waterfall and Gali Ali Beg Waterfall along the way.",
  },
  {
    question: "What's the best time to visit?",
    answer: "Spring (May-June) for wildflowers and green valleys. Autumn (Sep-Oct) for clear skies and golden foliage. March for Nawroz celebrations and the ZMT expedition. Winter (Dec-Feb) for snow sports and dramatic frozen landscapes. Each season offers a completely different experience.",
  },
  {
    question: "How do I book and what's the payment process?",
    answer: "Contact us via WhatsApp (+964 750 111 6377) or email (info@visitiraqikurdistan.com). A 30% deposit secures your spot, with the remaining 70% due one month before the tour. Spaces are limited — especially the Zagros Trail and Federal Iraq Tour — so early booking is strongly recommended.",
  },
  {
    question: "What's included in the Zagros Mountain Trail package?",
    answer: "Everything: airport transfers, 12 nights accommodation (homestays + hotels), all meals (breakfast, lunch, dinner), professional English-speaking guide, daily luggage transfers, all hiking permits, support vehicles, and Nawroz celebration in Akre. Not included: drinks, personal expenses, and tips for local guides.",
  },
  {
    question: "Can I do a private trip instead?",
    answer: "Absolutely. Private trips are available for groups of 3+ people at $150/person for a 2-day, 1-night experience that includes a Halgurd hike and optional Bekodyan Lake visit. Contact us for custom itineraries — we can tailor any adventure to your group's pace and interests.",
  },
];

export const WHY_VIK = [
  {
    title: "Local Born & Bred",
    description: "Founded by Omar Chomani, a Choman native. We don't just visit these mountains — we grew up in them. Every guide is local, every connection is real.",
    icon: "🏔️",
  },
  {
    title: "Safety First",
    description: "13+ years of experience, all permits secured, verified homestays, professional guides monitoring every stage. Your safety is non-negotiable.",
    icon: "🛡️",
  },
  {
    title: "Community Impact",
    description: "Every dollar stays in the community. Homestay families, local guides, village cooks — your adventure directly supports 30+ rural communities.",
    icon: "❤️",
  },
  {
    title: "Award-Winning",
    description: "Featured in NYT, National Geographic, Lonely Planet. ZMT won the 2025 BGTW Best Wider World Tourism Project award. Trusted by the world's best travel media.",
    icon: "🏆",
  },
];
